---
title: "Victorian Forest Futures Population Vability Analysis"
output: 
  html_notebook: 
    toc: yes
    number_sections: true
author: GE Ryan
date: 2019-08-05
---

# Preparations

### Packages
Load packages
```{r packages}
library(raster)
library(dplyr)
library(tibble)
library(sf)
library(rgdal)
library(readr)
library(readxl)
library(ggplot2)
library(lubridate)
library(magrittr)
library(tidyr)
```

### Functions
```{r functions}
source(file = "R/functions/gsfplot.R")
source(file = "R/functions/grplot.R") # fugly
source(file = "R/functions/read.vba.R")
```


# Prepare variables

## Geographic data

### Landscape
Set up base landscape layer
```{r ch_rst}
ch_rst <- raster(x = "data/grids/eco_v12.img")
ch_rst
```
```{r}
ch_proj <- crs(ch_rst)
```


```{r plot ch_rst}
plot(ch_rst)
```

### Boundaries
```{r rfa}
rfa <- read_sf("data/shapefiles/RFA/")
rfa
```

```{r}
gsfplot(rfa)
```


```{r ch_rfa}
ch_rfa <- rfa[rfa$NAME== "CENTRAL HIGHLANDS",] %>%
  st_transform(crs = ch_proj)

ch_rfa
```

```{r}
gsfplot(ch_rfa)
```


```{r ch_mask}
ch_mask <- rasterize(ch_rfa, ch_rst, field = 1)
```

```{r plot ch_mask}
plot(ch_mask)
```

```{r}
victoria <- read_sf("data/shapefiles/vicstatepolygon/") %>%
  st_transform(crs = ch_proj)
```




## Occurrence data

### GG Occurrence data
Read in data
```{r read gg occ}
gg_ari <- read_excel(path = "data/tabular/BoA_SB_Combined_VBA_upload_v4.xls") %>%
  dplyr::select(-starts_with("leave")) %>%
  rename("lon" = `X-coordinate (easting or longitude)`, "lat" = `Y-coordinate (northing or latitude)`) %>%
   fill(lon, lat, .direction = "down") %>%
  filter(`Taxon Name` == "Misc Target taxa not found") %>%
  select(lon, lat) %>%
  mutate(PA = 0) %>%
  st_as_sf(coords = c("lon", "lat"), crs = st_crs(28355)) %>%
  st_transform(crs = st_crs(ch_rst))

gg_ari
```

```{r}
gg_vba <- read.vba("data/tabular/vba_gg_all_20190509.csv") %>%
  dplyr::rename("date" = `Survey Start Date`, "lon" = `Longitude GDA94`, "lat" = `Latitude GDA94`, "count" = `Total Count`) %>%
  select(date, lon, lat, count) %>%
  mutate(date = dmy(date)) %>%
  filter(date > ymd("2009-03-01")) %>%
  mutate(PA = ifelse(count != 0 | is.na(count), 1, 0)) %>%
  select(lon, lat, PA) %>%
  st_as_sf(coords = c("lon", "lat"), crs = st_crs(4283)) %>%
  st_transform(crs = st_crs(ch_rst))

gg_vba
```
```{r gg_pa_all}
gg_pa_all <- gg_vba %>%
  rbind(gg_ari)

gg_pa_all
```

```{r plot_gg_pa_all}
plot_gg_pa_all <- ggplot() +
  geom_sf(data = victoria) +
  geom_sf(data = ch_rfa) +
  geom_sf(data = gg_pa_all, aes(colour = base::as.factor(PA)), size = 0.01)

plot_gg_pa_all
```

```{r gg_pa_ch}
gg_pa_ch <- gg_pa_all

gg_pa_ch
```



### LBP Occurrence data
```{r read lb occ}

```

## Landis output

## Climactic data

## Distribution model variables

# Distribution model fit and prediction

# Population viability analysis