---
title: "east_gippsland_fire_ecoregions_planned_burn.Rmd"
output: html_document
---

```{r}

```



## Planned burns

### RFA level
```{r}
eg_burn_annual <- burn_eg %>%
  full_join(
    y = tibble("season" = 1971:2020),
    by = "season"
  ) %>%
  group_by(season)%>%
  summarise %>%
  mutate(
    area_m2 = map(
      .x = geometry,
      .f = function(x){
        result <- x %>%
          st_area
      }
    )
  ) %>%
  unnest(area_m2) %>%
  mutate(
    area_ha = area_m2/10000,
    area_ha_burnt = ifelse(area_ha == 0, NA, area_ha),
    fire = ifelse(area_ha == 0, "No fire", "Fire")
    ) %>%
  dplyr::select(season, area_ha, area_ha_burnt, fire, geometry) %>%
  arrange(season)

eg_burn_annual
```


```{r}
br <- 10^(0:6)

ggplot(eg_burn_annual) +
  geom_boxplot(
    aes(
      y = area_ha_burnt
    )
  ) +
  scale_y_continuous(
    trans = "log10",
    breaks = br,
    labels = br
  ) +
  ggtitle("Area (ha) of fires in East Gippsland RFA zone, 1971-2020") +
  ylab("Area (ha)") +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )
```


```{r}
eg_burn_summary <- eg_burn_annual %>%
  as.data.frame %>%
  summarise(
    mean_area_ha = mean(area_ha),
    mean_area_ha_burnt = mean(area_ha_burnt, na.rm = TRUE),
    sd_area_ha = sd(area_ha),
    sd_area_ha_burnt = sd(area_ha_burnt, na.rm = TRUE),
    nyears = n(),
    nyears_fire = sum(fire == "Fire"),
    prop_years_fire = nyears_fire/nyears
  ) %>%
  as_tibble

glimpse(eg_fire_summary)
```


### By ecoregion

```{r}
eco_fire_annual <- st_intersection(
  eg_fire_annual,
  ecoregions
) %>%
  dplyr::select(Region, season, geometry) %>%
  arrange(Region, season) %>%
  full_join(
   y = expand.grid(
     "Region" = 1:19,
     "season" = 1971:2020
   ) %>%
     as_tibble,
   by = c("Region", "season")
  ) %>%
  mutate(
    area_m2 = map(
      .x = geometry,
      .f = function(x){
        result <- x %>%
          st_area
      }
    )
  ) %>%               
  unnest(area_m2) %>%
  mutate(
    area_ha = area_m2/10000,
    area_ha_burnt = ifelse(area_ha == 0, NA, area_ha),
    fire = ifelse(area_ha == 0, "No fire", "Fire"),
    region = as.factor(Region)
    ) %>%
  dplyr::select(region, season, area_ha, area_ha_burnt, fire, geometry) %>%
  arrange(region, season)
  

eco_fire_annual
```

```{r}
br <- 10^(0:5)

ggplot(eco_fire_annual) +
  geom_boxplot(
    aes(
      y = area_ha_burnt,
      x = region
    )
  ) +
  scale_y_continuous(
    trans = "log10",
    breaks = br,
    labels = br
  ) +
  ggtitle("Area (ha) of fires in East Gippsland Ecoregions, 1971-2020") +
  ylab("Area (ha)") +
  xlab("Ecoregion")
```


```{r}
eco_fire_summary <- eco_fire_annual %>%
  as.data.frame %>%
  group_by(region) %>%
  summarise(
    mean_area_ha = mean(area_ha),
    mean_area_ha_burnt = mean(area_ha_burnt, na.rm = TRUE),
    sd_area_ha = sd(area_ha),
    sd_area_ha_burnt = sd(area_ha_burnt, na.rm = TRUE),
    nyears = n(),
    nyears_fire = sum(fire == "Fire"),
    prop_years_fire = nyears_fire/nyears
  ) %>%
  as_tibble

eco_fire_summary[1:10,]
eco_fire_summary[11:19,]
```



```{r}
ggplot(eco_fire_summary) +
  geom_col(
    aes(
      x = region,
      y = prop_years_fire
    )
  ) +
  ylim(0, 1) +
  ylab("Proportion of years fire occurrs in ecoregion")
```

