---
title: "East Gippsland fire ecoregions"
output:
  word_document: default
  html_document:
    df_print: paged
---


```{r}
library(sf)
library(dplyr)
library(tibble)
library(magrittr)
library(lwgeom)
library(ggplot2)
library(raster)
library(purrr)
library(units)
library(tidyr)

load(file = "output/RData/00_controls.RData")
```


```{r}
rfa <- read_sf("data/shapefiles/RFA", crs = 4283) %>%
  st_transform(3111)

rfa
```

```{r}
plot(rfa["NAME"])
```


```{r}
egipp <- rfa[rfa$NAME == "EAST GIPPSLAND",]
```


```{r}
ggplot() +
  #geom_sf(data = fire_eg, fill = "red") +
  #scale_fill_viridis_c()+
  geom_sf(data = egipp, fill = NA)
```

```{r}
egbox <- st_bbox(egipp)
```



```{r}
ecoregions <- read_sf("data/shapefiles/EGipps_regions/EGipps_regions.shp", crs = 4283) %>%
  st_transform(3111) # VicGrid

ecoregions
```

```{r}
plot(ecoregions["Region"])
```

```{r}
ggplot(ecoregions) +
  geom_sf(aes(fill = Region %>% as.factor))
```


```{r}
fh_2020 <- raster(x = "data/grids/FireSeverityFinal_20200414.tif")

crs(fh_2020) <- CRS("+init=epsg:3111")

fh_2020
```


```{r}
# fheg <- crop(
#   x = fh_2020,
#   y = extent(egipp)
# )

fheg <- fh_2020
```


```{r}
fheg[getValues(fheg) < 1] <- NA
fheg[getValues(fheg) > 0] <- 1

fheg
```

```{r}
fheg <- aggregate(
  x = fheg,
  fact = 5,
  fun = sum,
  na.rm = TRUE
)
```

```{r}
fheg[getValues(fheg) < 13] <- NA
fheg[!is.na(getValues(fheg))] <- 1
```



```{r}
fh_2020_poly <- rasterToPolygons(
  x = fheg,
  fun = function(x){
    ifelse(x == 0, FALSE, TRUE)
  },
  dissolve = TRUE
)
```


```{r}
fh20 <- st_as_sf(fh_2020_poly) %>%
  st_transform(3111)


fh20 <- tibble(
    season = 2020,
    geometry = fh20$geometry[1]
  ) %>%
  st_as_sf

fh20
```

```{r}
fh20_poly <- st_cast(fh20, "POLYGON")

fh20_int_eg <- st_intersects(
  x = fh20_poly,
  y = egipp,
  sparse = FALSE
) %>%
  apply(
    MARGIN = 1,
    FUN = any
  )


fh20_eg <- cbind(
 fh20_poly,
  fh20_int_eg
) %>%
  filter(fh20_int_eg) %>%
  dplyr::select(season, geometry) %>%
  st_cast(to = "MULTIPOLYGON") %>%
  mutate(
    area_m2 = map(
      .x = geometry,
      .f = function(x){
        result <- x %>%
          st_area
      }
    )
  ) %>%
  unnest(area_m2)%>%
  arrange(desc(area_m2))

fh20_eg
```


```{r}
ggplot() + 
  geom_sf(
    data = egipp,
    colour = "black"
  ) +
  geom_sf(
    data = fh20_eg,
    aes(fill = log10(area_m2)),
    alpha = 0.5
  ) +
  scale_fill_viridis_c()
```


```{r}
ggplot() + 
  geom_sf(
    data = egipp,
    colour = "black"
  ) +
  geom_sf(
    data = fh20_eg[1,],
    aes(fill = log10(area_m2)),
    alpha = 0.5
  ) +
  scale_fill_viridis_c()
```

```{r}
ggplot() + 
  geom_sf(
    data = egipp,
    colour = "black"
  ) +
  geom_sf(
    data = fh20_eg[2,],
    aes(fill = log10(area_m2)),
    alpha = 0.5
  ) +
  scale_fill_viridis_c()
```

```{r}
ggplot() + 
  geom_sf(
    data = egipp,
    colour = "black"
  ) +
  geom_sf(
    data = fh20_eg[3,],
    aes(fill = log10(area_m2)),
    alpha = 0.5
  ) +
  scale_fill_viridis_c()
```

```{r}
ggplot() + 
  geom_sf(
    data = egipp,
    colour = "black"
  ) +
  geom_sf(
    data = fh20_eg[4:113,],
    aes(fill = log10(area_m2)),
    alpha = 0.5
  ) +
  scale_fill_viridis_c()
```

Lines 2 & 2 are probably the same fire:
```{r}
st_distance(fh20_eg[2,], fh20_eg[3,])
```

```{r}
ggplot() + 
  geom_sf(
    data = egipp,
    colour = "black"
  ) +
  geom_sf(
    data = fh20_eg[2:3,],
    aes(fill = log10(area_m2)),
    alpha = 0.5
  ) +
  scale_fill_viridis_c()
```

Lines 1 and 4:113 likely the same fire also:
```{r}
ggplot() + 
  geom_sf(
    data = egipp,
    colour = "black"
  ) +
  geom_sf(
    data = fh20_eg[c(1, 4:113),],
    aes(fill = log10(area_m2)),
    alpha = 0.5
  ) +
  scale_fill_viridis_c()
```


```{r}

fh20 <- st_as_sf(fh_2020_poly) %>%
  st_transform(3111)


fh20 <- tibble(
    season = 2020,
    geometry = fh20$geometry[1]
  ) %>%
  st_as_sf

fh20
```


```{r}
f20_1 <- st_combine(fh20_eg[c(1, 4:113),])

f20_2 <- st_combine(fh20[2:3,])
```


```{r}
fh20_1 <- tibble(
    season = 2020,
    geometry = f20_1
  ) %>%
  st_as_sf

fh20_1
```

```{r}
fh20_2 <- tibble(
    season = 2020,
    geometry = f20_2
  ) %>%
  st_as_sf

fh20_2
```


```{r}
fire_history <- read_sf("data/shapefiles/DELWP_2019_interim_fire") %>%
  st_transform(3111)
  

fire_history
```

```{r}
bushfire <- fire_history %>%
  filter(season > 1970) %>%
  filter(firetype == "BUSHFIRE") %>%
  dplyr::select(season) %>%
  rbind(
    fh20_1,
    fh20_2
  )


bushfire
```

```{r}
burn <- fire_history %>%
  filter(season > 2009) %>%
  filter(firetype == "BURN") %>%
  dplyr::select(season)

burn
```

```{r}
fire_eg <- st_intersection(
  bushfire,
  egipp
) %>%
  dplyr::select(season, geometry) %>%
  arrange(season)

fire_eg
```


```{r}
fire_in_eg <- st_intersects(
  x = bushfire,
  y = egipp,
  sparse = FALSE
) %>%
  apply(
    MARGIN = 1,
    FUN = any
  )


fs_eg <- cbind(
  bushfire,
  fire_in_eg
) %>%
  filter(fire_in_eg)%>%
  dplyr::select(season, geometry) %>%
  arrange(season) %>%
  as_tibble %>%
  st_as_sf

fs_eg
```



```{r}
burn_eg <- st_intersection(
  burn,
  egipp
) %>%
  dplyr::select(season, geometry) %>%
  arrange(season)

burn_eg
```

## Bushfire area burnt

### RFA level
```{r}
eg_fire_annual <- fire_eg %>%
  full_join(
    y = tibble("season" = 1971:2020),
    by = "season"
  ) %>%
  group_by(season)%>%
  summarise %>%
  mutate(
    area_m2 = map(
      .x = geometry,
      .f = function(x){
        result <- x %>%
          st_area
      }
    )
  ) %>%
  unnest(area_m2) %>%
  mutate(
    area_ha = area_m2/10000,
    area_ha_burnt = ifelse(area_ha == 0, NA, area_ha),
    fire = ifelse(area_ha == 0, "No fire", "Fire")
    ) %>%
  dplyr::select(season, area_ha, area_ha_burnt, fire, geometry) %>%
  arrange(season)

eg_fire_annual
```


```{r}
br <- 10^(0:6)

ggplot(eg_fire_annual) +
  geom_boxplot(
    aes(
      y = area_ha_burnt
    )
  ) +
  scale_y_continuous(
    trans = "log10",
    breaks = br,
    labels = br
  ) +
  ggtitle("Area (ha) of fires in East Gippsland RFA zone, 1971-2020") +
  ylab("Area (ha)") +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )
```


```{r}
eg_fire_summary <- eg_fire_annual %>%
  as.data.frame %>%
  summarise(
    mean_area_ha = mean(area_ha),
    mean_area_ha_burnt = mean(area_ha_burnt, na.rm = TRUE),
    sd_area_ha = sd(area_ha),
    sd_area_ha_burnt = sd(area_ha_burnt, na.rm = TRUE),
    min_area_ha_burnt = min(area_ha_burnt, na.rm = TRUE),
    max_area_ha_burnt = max(area_ha_burnt, na.rm = TRUE),
    nyears = n(),
    nyears_fire = sum(fire == "Fire"),
    prop_years_fire = nyears_fire/nyears
  ) %>%
  as_tibble

glimpse(eg_fire_summary)
```

```{r}
write.csv(
  x = eg_fire_summary,
  file = "eg_fire_summary.csv",
  row.names = FALSE
)
```


### By ecoregion

```{r}
eco_fire_annual <- st_intersection(
  eg_fire_annual,
  ecoregions
) %>%
  dplyr::select(Region, season, geometry) %>%
  arrange(Region, season) %>%
  full_join(
   y = expand.grid(
     "Region" = 1:19,
     "season" = 1971:2020
   ) %>%
     as_tibble,
   by = c("Region", "season")
  ) %>%
  mutate(
    area_m2 = map(
      .x = geometry,
      .f = function(x){
        result <- x %>%
          st_area
      }
    )
  ) %>%               
  unnest(area_m2) %>%
  mutate(
    area_ha = area_m2/10000,
    area_ha_burnt = ifelse(area_ha == 0, NA, area_ha),
    fire = ifelse(area_ha == 0, "No fire", "Fire"),
    region = as.factor(Region)
    ) %>%
  dplyr::select(region, season, area_ha, area_ha_burnt, fire, geometry) %>%
  arrange(region, season)
  

eco_fire_annual
```

```{r}
br <- 10^(0:5)

ggplot(eco_fire_annual) +
  geom_boxplot(
    aes(
      y = area_ha_burnt,
      x = region
    )
  ) +
  scale_y_continuous(
    trans = "log10",
    breaks = br,
    labels = br
  ) +
  ggtitle("Area (ha) of fires in East Gippsland Ecoregions, 1971-2020") +
  ylab("Area (ha)") +
  xlab("Ecoregion")
```


```{r}
eco_fire_summary <- eco_fire_annual %>%
  as.data.frame %>%
  group_by(region) %>%
  summarise(
    mean_area_ha = mean(area_ha),
    mean_area_ha_burnt = mean(area_ha_burnt, na.rm = TRUE),
    sd_area_ha = sd(area_ha),
    sd_area_ha_burnt = sd(area_ha_burnt, na.rm = TRUE),
    min_area_ha_burnt = min(area_ha_burnt, na.rm = TRUE),
    max_area_ha_burnt = max(area_ha_burnt, na.rm = TRUE),
    nyears = n(),
    nyears_fire = sum(fire == "Fire"),
    prop_years_fire = nyears_fire/nyears
  ) %>%
  as_tibble

eco_fire_summary[1:10,]
eco_fire_summary[11:19,]
```

```{r}
write.table(
  x = eco_fire_summary,
  file = "eco_fire_summary.csv",
  row.names = FALSE
)
```


```{r}
all_fire_summary <- rbind(
  bind_cols(
    tibble(region = "RFA"),
    eg_fire_summary
  ),
  eco_fire_summary %>%
  mutate(region = as.character(region))
)

all_fire_summary
```

```{r}
write.csv(
  x = all_fire_summary,
  file = "eg_eco_fire_summary.csv",
  row.names = FALSE
)
```



```{r}
ggplot(eco_fire_summary) +
  geom_col(
    aes(
      x = region,
      y = prop_years_fire
    )
  ) +
  ylim(0, 1) +
  ylab("Proportion of years fire occurrs in ecoregion")
```


## Bushfire fire size
```{r}
fire_size_eg <- fs_eg %>%
  mutate(
    area_m2 = map(
      .x = geometry,
      .f = function(x){
        result <- x %>%
          st_area
      }
    )
  ) %>%
  unnest(area_m2)%>%
  mutate(
    area_ha = area_m2/10000,
    ) %>%
  dplyr::select(season, area_ha, geometry) %>%
  arrange(s)


fire_size_eg
```

```{r}
fire_size_eg_summary  <- fire_size_eg %>%
  as.data.frame %>%
  summarise(
    max_fire_ha = max(area_ha),
    min_fire_ha = min(area_ha),
    mean_fire_ha = mean(area_ha),
    median_fire_ha = median(area_ha),
    sd_fire_ha = sd(area_ha),
    mean_n_fires_per_year = n()/50
  ) %>%
  as_tibble

glimpse(fire_size_eg_summary)
```

```{r}
fs_log_rfa <- fire_size_eg %>%
  as.data.frame %>%
  mutate(
    ln_area_ha = log(area_ha)
  ) %>%
  summarise(
    meanlog_area_ha = mean(ln_area_ha),
    sdlog_area_ha = sd(ln_area_ha)
  ) %>%
  as_tibble

fs_log_rfa
```



```{r}
nfires_hist_eg_rfa_summary <- fire_size_eg %>%
  as.data.frame %>%
  dplyr::select(season) %>%
  group_by(season) %>%
  summarise(
    nfires = n()
  ) %>%
  ungroup %>%
  full_join(expand.grid(season = 1971:2020)) %>%
  mutate(
    nfires = ifelse(
      is.na(nfires),
      0,
      nfires
    )
  ) %>%
  as_tibble %>%
  summarise(
    max_nfires = max(nfires),
    min_nfires = min(nfires),
    mean_nfires = mean(nfires),
    median_nfires = median(nfires),
    sd_nfires = sd(nfires)
  )

nfires_hist_eg_rfa_summary
```

```{r}
glimpse(nfires_hist_eg_rfa_summary)
```


```{r}
eco_fs_int <- st_intersects(
  x = fire_size_eg,
  y = ecoregions,
  sparse = FALSE
)
```

```{r}
e_int <- cbind(
  fire_size_eg %>%
    as.data.frame %>%
    dplyr::select(season, area_ha),
  eco_fs_int %>%
    as.data.frame
) %>%
  pivot_longer(
    cols = starts_with("V"),
    names_to = "region",
    names_prefix = "V",
    values_to = "intersects"
  ) %>%
  filter(intersects) %>%
  dplyr::select(season, region, area_ha)
    
e_int
```
```{r}
eco_fire_size_eg_summary <- e_int %>%
  group_by(region) %>%
  summarise(
    max_fire_ha = max(area_ha),
    min_fire_ha = min(area_ha),
    mean_fire_ha = mean(area_ha),
    median_fire_ha = median(area_ha),
    sd_fire_ha = sd(area_ha),
    mean_n_fires_per_year = n()/50
  ) %>%
  as_tibble

eco_fire_size_eg_summary
```

```{r}
fs_log_eco <- e_int %>%
  mutate(
    ln_area_ha = log(area_ha)
  ) %>%
  group_by(region) %>%
  summarise(
    meanlog_area_ha = mean(ln_area_ha),
    sdlog_area_ha = sd(ln_area_ha)
  ) %>% 
  mutate(region = as.numeric(region)) %>%
  arrange(region)

fs_log_eco
```

```{r}
nfires_hist_eg_eco_summary <- e_int %>%
  group_by(region, season) %>%
  summarise(
    nfires = n()
  ) %>%
  ungroup %>%
  full_join(
    expand.grid(
      season = 1971:2020,
      region = 1:19 %>% as.character
    )
  ) %>%
  mutate(
    nfires = ifelse(
      is.na(nfires),
      0,
      nfires
    )
  ) %>%
  as_tibble %>%
  group_by(region) %>%
  summarise(
    max_nfires = max(nfires),
    min_nfires = min(nfires),
    mean_nfires = mean(nfires),
    median_nfires = median(nfires),
    sd_nfires = sd(nfires)
  )

nfires_hist_eg_eco_summary
```



```{r}
all_fire_size_summary <- rbind(
  bind_cols(
    tibble(region = "RFA"),
    fire_size_eg_summary
  ),
  eco_fire_size_eg_summary
)

all_fire_size_summary
```

```{r}
write.csv(
  x = all_fire_size_summary,
  file = "eg_eco_fire_size_summary.csv",
  row.names = FALSE
)
```


```{r}
fire_size_hist_eg_rfa <- fire_size_eg %>%
  as.data.frame %>%
  dplyr::select(season, area_ha) %>%
  as_tibble

fire_size_hist_eg_rfa
```

```{r}
fire_size_hist_eg_eco <- e_int

fire_size_hist_eg_eco
```

```{r}
fire_hist_eg_summary <- rbind(
  bind_cols(
    tibble(region = "RFA"),
    fire_size_eg_summary,
    nfires_hist_eg_rfa_summary
  ),
  full_join(
    x = eco_fire_size_eg_summary,
    y = nfires_hist_eg_eco_summary,
    by = "region"
  )
)


fire_hist_eg_summary
```

```{r}
saveRDS(
  object = fire_size_hist_eg_rfa,
  file = "output/fire_size_hist_eg_rfa.Rds"
)

saveRDS(
  object = fire_size_hist_eg_eco,
  file = "output/fire_size_hist_eg_eco.Rds"
)


saveRDS(
  object = fire_hist_eg_summary,
  file = "output/fire_hist_eg_summary.Rds"
)

save.image(file = "output/eg_fire_hist_summaries.RData")
```




