---
title: "Victorian Forest Futures Population Vability Analysis: Central Highlands"
output: 
  html_notebook: 
    toc: yes
    number_sections: true
author: GE Ryan
date: 2019-08-05
---

# Project setup

### Packages
Load packages
```{r packages}
library(raster)
library(dplyr)
library(tibble)
library(sf)
library(rgdal)
library(readr)
library(readxl)
library(ggplot2)
library(lubridate)
library(magrittr)
library(tidyr)
```

### Functions
```{r functions}
source(file = "R/functions/pf_sf.R")
#source(file = "R/functions/grplot.R") # fugly
source(file = "R/functions/read.vba.R")
```


# Prepare variables

## Geographic data

### Landscape
Set up base landscape layer
```{r ch_rst}
ch_rst <- raster(x = "data/grids/eco_v12.img") %>%
  projectRaster(from = ., crs = crs("+init=epsg:32755"), method = "ngb")

ch_rst
```
```{r}
ch_proj <- ch_rst@crs
ch_extent <- extent(ch_rst)
ch_res <- res(ch_rst)
```


```{r plot ch_rst}
plot(ch_rst)
```

### Boundaries
```{r rfa}
rfa <- read_sf("data/shapefiles/RFA/")%>%
  st_transform(crs = ch_proj)
rfa
```

```{r}
pf.sf(rfa)
```


```{r ch_rfa}
ch_rfa <- rfa[rfa$NAME== "CENTRAL HIGHLANDS",]

ch_rfa
```

```{r}
pf.sf(ch_rfa)
```


```{r ch_mask}
ch_mask <- rasterize(ch_rfa, ch_rst, field = 1)

ch_mask
```

```{r plot ch_mask}
plot(ch_mask)
```

```{r}
victoria <- read_sf("data/shapefiles/vicstatepolygon/") %>%
  st_transform(crs = ch_proj)
```




## Occurrence data

### GG Occurrence data
Read in data
```{r gg_ari}
gg_ari <- read_excel(path = "data/tabular/BoA_SB_Combined_VBA_upload_v4.xls") %>%
  dplyr::select(-starts_with("leave")) %>%
  rename("lon" = `X-coordinate (easting or longitude)`, "lat" = `Y-coordinate (northing or latitude)`) %>%
   fill(lon, lat, .direction = "down") %>%
  filter(`Taxon Name` == "Misc Target taxa not found") %>%
  select(lon, lat) %>%
  mutate(PA = 0) %>%
  st_as_sf(coords = c("lon", "lat"), crs = st_crs(28355)) %>%
  st_transform(crs = st_crs(ch_rst))

gg_ari
```

```{r gg_vba}
gg_vba <- read.vba("data/tabular/vba_gg_all_20190509.csv") %>%
  dplyr::rename("date" = `Survey Start Date`, "lon" = `Longitude GDA94`, "lat" = `Latitude GDA94`, "count" = `Total Count`) %>%
  select(date, lon, lat, count) %>%
  mutate(date = dmy(date)) %>%
  filter(date > ymd("2009-03-01")) %>%
  mutate(PA = ifelse(count != 0 | is.na(count), 1, 0)) %>%
  select(lon, lat, PA) %>%
  st_as_sf(coords = c("lon", "lat"), crs = st_crs(4283)) %>%
  st_transform(crs = st_crs(ch_rst))

gg_vba
```
```{r gg_pa_all}
gg_pa_all <- gg_vba %>%
  rbind(gg_ari)

gg_pa_all
```

```{r plot_gg_pa_all}
plot_gg_pa_all <- pg.pa(gg_pa_all, ch_rfa) +
  geom_sf(data = victoria, fill = NA)

plot_gg_pa_all
```

```{r gg_pa_ch}
gg_pa_ch <- gg_pa_all[ch_rfa,]
gg_pa_ch
```


```{r pg_gg_pa_ch}
pg_gg_pa_ch <- pg.pa(gg_pa_ch, ch_rfa)

pg_gg_pa_ch
```

### LBP Occurrence data
```{r read lb occ}
lb_pa <- proc.vba("data/tabular/vba_lb_all_20190509.csv")

lb_pa
```
```{r}
read.vba("data/tabular/vba_lb_all_20190509.csv") %>%
  dplyr::rename("date" = `Survey Start Date`, "lon" = `Longitude GDA94`, "lat" = `Latitude GDA94`, "count" = `Total Count`) %>%
  select(date, lon, lat, count) %>%
  mutate(date = dmy(date)) %>%
  filter(date > ymd("2009-03-01")) %>%
  mutate(PA = ifelse(count != 0 | is.na(count), 1, 0)) %>%
  select(lon, lat, PA) %>%
  st_as_sf(coords = c("lon", "lat"), crs = st_crs(4283)) %>%
  st_transform(crs = st_crs(ch_rst))

```
```{r}
zz <- length(readLines("data/tabular/vba_lb_all_20190509.csv"))
  
xx <-  readLines("data/tabular/vba_gg_all_20190509.csv") %>%
    head(-7) %>%
    #paste0(collapse = "\n") %>%
    read_csv(skip = 15, guess_max = zz-7)
```


## Landis output

## Climactic data

## Distribution model variables

# Distribution model fit and prediction

# Population viability analysis