---
title: "LANDIS Reprojections"
author: "GE Ryan"
date: "06/10/2020"
output: html_document
---

```{r}
library(raster)
library(rgdal)
library(dplyr)
```

```{r}
source("R/functions/source.functions.R")
source.functions(x = "R/functions")
```


```{r}
dirpath <- "C:/Users/ryange/OneDrive - The University of Melbourne/unimelb_work/RFA_STEPS"
```

```{r}
rgdal::setCPLConfigOption("GDAL_PAM_ENABLED", "FALSE") # stops writeRaster writing xml files.
```


```{r}
ecoeg <- proc.ras.eg(x = "EG19_fc/Ecoregion_EG.img") 

ecoeg
```

```{r}
ec <- proc.ras.eg(x = "EG19_fc/Ecoregion_EG.img")
ic19 <- proc.ras.eg(x = "EG19_fc/IC_EG_2019.img")
ic20 <- proc.ras.eg(x = "EG19_fc/IC_EG_2020.img")
ma <- proc.ras.eg(x = "EG19_fc/Zones_EG.img")
st <- proc.ras.eg(x = "EG19_fc/Stands_EG.img")
fe <- proc.ras.eg(x = "EG19_fc/FireEco.img")
sl <- proc.ras.eg(x = "EG19_fc/Slope_EG.img")
as <- proc.ras.eg(x = "EG19_fc/Aspect_EG.img")
```


## Rescale to 40000m2
```{r}
l4_ec_a <- raster::aggregate(ec, fact = 2, fun = most.freq)
l4_ic19_a <- raster::aggregate(ic19, fact = 2, fun = most.freq)
l4_ic20_a <- raster::aggregate(ic20, fact = 2, fun = most.freq)
l4_ma_a <- raster::aggregate(ma, fact = 2, fun = set.nth)
l4_st_a <- raster::aggregate(st, fact = 2, fun = set.nth)
l4_fe_a <- raster::aggregate(fe, fact = 2, fun = most.freq)
l4_sl_a <- raster::aggregate(sl, fact = 2, fun = function(x, na.rm = TRUE){as.integer(mean(x, na.rm = na.rm))})
l4_as_a <- raster::aggregate(as, fact = 2, aspect.avg)
```

```{r}
l4_ec_a
```

```{r}
plot(l4_ic19_a)
```


```{r}
plot(l4_st_a)
```


```{r}
plot(l4_ma_a)
```


```{r}
vst <- getValues(l4_st_a)
vma <- getValues(l4_ma_a)
```



```{r}
writeRaster(x = l4_ec_a,   filename = paste0(dirpath, "/", "EG2019_400/Ecoregion_EG.img"), format = "HFA", datatype = "INT4S", overwrite = TRUE, NAflag = -Inf)
writeRaster(x = l4_ic19_a, filename = paste0(dirpath, "/", "EG2019_400/IC_EG_2019.img"),   format = "HFA", datatype = "INT4S", overwrite = TRUE, NAflag = 0)
writeRaster(x = l4_ic20_a, filename = paste0(dirpath, "/", "EG2019_400/IC_EG_2020.img"),   format = "HFA", datatype = "INT4S", overwrite = TRUE, NAflag = 0)
writeRaster(x = l4_ma_a,   filename = paste0(dirpath, "/", "EG2019_400/Zones_EG.img"),     format = "HFA", datatype = "INT4S", overwrite = TRUE, NAflag = 0)
writeRaster(x = l4_st_a,   filename = paste0(dirpath, "/", "EG2019_400/Stands_EG.img"),    format = "HFA", datatype = "INT4S", overwrite = TRUE, NAflag = 0)
writeRaster(x = l4_fe_a,   filename = paste0(dirpath, "/", "EG2019_400/FireEco.img"),      format = "HFA", datatype = "INT4S", overwrite = TRUE, NAflag = 0)
writeRaster(x = l4_sl_a,   filename = paste0(dirpath, "/", "EG2019_400/Slope_EG.img"),     format = "HFA", datatype = "INT2S", overwrite = TRUE, NAflag = 0)
writeRaster(x = l4_as_a,   filename = paste0(dirpath, "/", "EG2019_400/Aspect_EG.img"),    format = "HFA", datatype = "INT2S", overwrite = TRUE, NAflag = 0)
```


## rescale to 1 km2 
```{r}
l1k_ec_a <- raster::aggregate(ec, fact = 10, fun = most.freq)
l1k_ic19_a <- raster::aggregate(ic19, fact = 10, fun = most.freq)
l1k_ic20_a <- raster::aggregate(ic20, fact = 10, fun = most.freq)
l1k_ma_a <- raster::aggregate(ma, fact = 10, fun = most.freq)
l1k_st_a <- raster::aggregate(st, fact = 10, fun = most.freq)
l1k_fe_a <- raster::aggregate(fe, fact = 10, fun = most.freq)
l1k_sl_a <- raster::aggregate(sl, fact = 10, fun = function(x, na.rm = TRUE){as.integer(mean(x, na.rm = na.rm))})
l1k_as_a <- raster::aggregate(as, fact = 10, aspect.avg)
```

```{r}
l1k_ec_a
```

```{r}
plot(l1k_ic19_a)
```



```{r}
writeRaster(x = l1k_ec_a,   filename = paste0(dirpath, "/", "EG2019_1km/Ecoregion_EG.img"), format = "HFA", datatype = "INT4S", overwrite = TRUE, NAflag = -Inf)
writeRaster(x = l1k_ic19_a, filename = paste0(dirpath, "/", "EG2019_1km/IC_EG_2019.img"),   format = "HFA", datatype = "INT4S", overwrite = TRUE, NAflag = 0)
writeRaster(x = l1k_ic20_a, filename = paste0(dirpath, "/", "EG2019_1km/IC_EG_2020.img"),   format = "HFA", datatype = "INT4S", overwrite = TRUE, NAflag = 0)
writeRaster(x = l1k_ma_a,   filename = paste0(dirpath, "/", "EG2019_1km/Zones_EG.img"),     format = "HFA", datatype = "INT4S", overwrite = TRUE)
writeRaster(x = l1k_st_a,   filename = paste0(dirpath, "/", "EG2019_1km/Stands_EG.img"),    format = "HFA", datatype = "INT4S", overwrite = TRUE)
writeRaster(x = l1k_fe_a,   filename = paste0(dirpath, "/", "EG2019_1km/FireEco.img"),      format = "HFA", datatype = "INT4S", overwrite = TRUE)
writeRaster(x = l1k_sl_a,   filename = paste0(dirpath, "/", "EG2019_1km/Slope_EG.img"),     format = "HFA", datatype = "INT2S", overwrite = TRUE, NAflag = 0) # note only 16 bit data type and NA flag that's within range of possible values
writeRaster(x = l1k_as_a,   filename = paste0(dirpath, "/", "EG2019_1km/Aspect_EG.img"),    format = "HFA", datatype = "INT2S", overwrite = TRUE, NAflag = 0) # note only 16 bit data type and NA flag that's within range of possible values
```



```{r}
#ect <- raster(x = "C:/Users/ryange/OneDrive - The University of Melbourne/unimelb_work/RFA_STEPS/EG19_fc/Ecoregion_EG.img")
#ic <- raster(x = "C:/Users/ryange/OneDrive - The University of Melbourne/unimelb_work/RFA_STEPS/EG19_fc/IC_EG_2019.img")

writeRaster(x = l1k_ec_a, filename = paste0(dirpath, "/", "EG2019_1km/Ecoregion_EG.asc"), format = "ascii", datatype = "INT4S", overwrite = TRUE)
writeRaster(x = l1k_ic19_a, filename = paste0(dirpath, "/", "EG2019_1km/IC_EG_2019.asc"), format = "ascii", datatype = "INT4S", overwrite = TRUE)
```

