---
title: "Metapopulation capacity results"
output:
  word_document: default
  html_document: default
---

```{r}
knitr::opts_chunk$set(fig.width=8, fig.height=8)
```


```{r}
source("R/spartan/spartan_settings.R")
```


```{r}
library(dplyr)
library(purrr)
library(tibble)
library(tidyr)
library(magrittr)
library(ggplot2)
library(raster)
```

```{r}
load(file = "output/RData/00_controls.RData")
load(file = "output/RData/01_landscape_variables.RData")
load(file = "output/RData/19_mpc_results_summary.RData")
```

```{r}
source.functions("R/functions")
```


## LBP


###  RAW
```{r}
p_mss_min_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_min
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_mss_min_gyle
```

```{r}
p_mss_med_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_median
    )
  ) +
  labs(
    x = "Median metapopulation capacity",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_mss_med_gyle
```

```{r}
p_m07_min_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_min_07
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity\n70% threshold",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_m07_min_gyle
```

```{r}
p_m07_med_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_median_07
    )
  ) +
  labs(
    x = "Median metapopulation capacity\n70% threshold",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_m07_med_gyle
```

```{r}
p_m05_min_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_min_05
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity\n50% threshold",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_m05_min_gyle
```

```{r}
p_m05_med_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_median_05
    )
  ) +
  labs(
    x = "Median metapopulation capacity\n50% threshold",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_m05_med_gyle
```

###  delta
```{r}
p_dmss_min_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_min
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_dmss_min_gyle
```

```{r}
p_dmss_med_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_median
    )
  ) +
  labs(
    x = "Change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_dmss_med_gyle
```

```{r}
p_dm07_min_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_min_07
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity (70% threshold)\n from baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_dm07_min_gyle
```

```{r}
p_dm07_med_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_median_07
    )
  ) +
  labs(
    x = "Change in median metapopulation capacity (70% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_dm07_med_gyle
```

```{r}
p_dm05_min_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_min_05
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )

p_dm05_min_gyle
```

```{r}
p_dm05_med_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_median_05
    )
  ) +
  labs(
    x ="Change in median metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_dm05_med_gyle
```

### delta proportional
```{r}
p_pmss_min_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_min
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_pmss_min_gyle
```

```{r}
p_pmss_med_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_median
    )
  ) +
  labs(
    x = "Proportional change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_pmss_med_gyle
```

```{r}
p_pm07_min_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_min_07
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity (70% threshold)\n from baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_pm07_min_gyle
```

```{r}
p_pm07_med_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_median_07
    )
  ) +
  labs(
    x = "Proportional change in median metapopulation capacity (70% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_pm07_med_gyle
```

```{r}
p_pm05_min_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_min_05
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )

p_pm05_min_gyle
```

```{r}
p_pm05_med_gyle <- ggplot(data = mpc_rs %>% filter(sp == "gyle")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_median_05
    )
  ) +
  labs(
    x ="Proportional change in median metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Leadbeater's possum"
  )
p_pm05_med_gyle
```

## Sooty Owl
###  RAW
```{r}
p_mss_min_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_min
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_mss_min_tyte
```

```{r}
p_mss_med_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_median
    )
  ) +
  labs(
    x = "Median metapopulation capacity",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_mss_med_tyte
```

```{r}
p_m07_min_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_min_07
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity\n70% threshold",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_m07_min_tyte
```

```{r}
p_m07_med_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_median_07
    )
  ) +
  labs(
    x = "Median metapopulation capacity\n70% threshold",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_m07_med_tyte
```

```{r}
p_m05_min_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_min_05
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity\n50% threshold",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_m05_min_tyte
```

```{r}
p_m05_med_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_median_05
    )
  ) +
  labs(
    x = "Median metapopulation capacity\n50% threshold",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_m05_med_tyte
```

###  delta
```{r}
p_dmss_min_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_min
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_dmss_min_tyte
```

```{r}
p_dmss_med_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_median
    )
  ) +
  labs(
    x = "Change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_dmss_med_tyte
```

```{r}
p_dm07_min_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_min_07
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity (70% threshold)\n from baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_dm07_min_tyte
```

```{r}
p_dm07_med_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_median_07
    )
  ) +
  labs(
    x = "Change in median metapopulation capacity (70% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_dm07_med_tyte
```

```{r}
p_dm05_min_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_min_05
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Sooty Owl"
  )

p_dm05_min_tyte
```

```{r}
p_dm05_med_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_median_05
    )
  ) +
  labs(
    x ="Change in median metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_dm05_med_tyte
```

### delta proportional
```{r}
p_pmss_min_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_min
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_pmss_min_tyte
```

```{r}
p_pmss_med_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_median
    )
  ) +
  labs(
    x = "Proportional change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_pmss_med_tyte
```

```{r}
p_pm07_min_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_min_07
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity (70% threshold)\n from baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_pm07_min_tyte
```

```{r}
p_pm07_med_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_median_07
    )
  ) +
  labs(
    x = "Proportional change in median metapopulation capacity (70% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_pm07_med_tyte
```

```{r}
p_pm05_min_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_min_05
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Sooty Owl"
  )

p_pm05_min_tyte
```

```{r}
p_pm05_med_tyte <- ggplot(data = mpc_rs %>% filter(sp == "tyte")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_median_05
    )
  ) +
  labs(
    x ="Proportional change in median metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "Sooty Owl"
  )
p_pm05_med_tyte
```


## PVA Species
###  RAW
```{r}
p_mss_min_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_min
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_mss_min_pva
```

```{r}
p_mss_med_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_median
    )
  ) +
  labs(
    x = "Median metapopulation capacity",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_mss_med_pva
```

```{r}
p_m07_min_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_min_07
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity\n70% threshold",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_m07_min_pva
```

```{r}
p_m07_med_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_median_07
    )
  ) +
  labs(
    x = "Median metapopulation capacity\n70% threshold",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_m07_med_pva
```

```{r}
p_m05_min_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_min_05
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity\n50% threshold",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_m05_min_pva
```

```{r}
p_m05_med_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_median_05
    )
  ) +
  labs(
    x = "Median metapopulation capacity\n50% threshold",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_m05_med_pva
```

###  delta
```{r}
p_dmss_min_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_min
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dmss_min_pva
```

```{r}
p_dmss_med_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_median
    )
  ) +
  labs(
    x = "Change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dmss_med_pva
```

```{r}
p_dm07_min_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_min_07
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity (70% threshold)\n from baseline (ongoing harvest)",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dm07_min_pva
```

```{r}
p_dm07_med_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_median_07
    )
  ) +
  labs(
    x = "Change in median metapopulation capacity (70% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dm07_med_pva
```

```{r}
p_dm05_min_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_min_05
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()

p_dm05_min_pva
```

```{r}
p_dm05_med_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_median_05
    )
  ) +
  labs(
    x ="Change in median metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dm05_med_pva
```

### delta proportional
```{r}
p_pmss_min_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_min
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pmss_min_pva
```

```{r}
p_pmss_med_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_median
    )
  ) +
  labs(
    x = "Proportional change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pmss_med_pva
```

```{r}
p_pm07_min_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_min_07
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity (70% threshold)\n from baseline (ongoing harvest)",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pm07_min_pva
```

```{r}
p_pm07_med_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_median_07
    )
  ) +
  labs(
    x = "Proportional change in median metapopulation capacity (70% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pm07_med_pva
```

```{r}
p_pm05_min_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_min_05
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()

p_pm05_min_pva
```

```{r}
p_pm05_med_pva <- ggplot(data = mpc_rs %>% filter(sp_group == "PVA")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_median_05
    )
  ) +
  labs(
    x ="Proportional change in median metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "PVA species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pm05_med_pva
```


## MPC Species
###  RAW
```{r}
p_mss_min_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_min
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_mss_min_mpc
```

```{r}
p_mss_med_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_median
    )
  ) +
  labs(
    x = "Median metapopulation capacity",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_mss_med_mpc
```

```{r}
p_m07_min_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_min_07
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity\n70% threshold",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_m07_min_mpc
```

```{r}
p_m07_med_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_median_07
    )
  ) +
  labs(
    x = "Median metapopulation capacity\n70% threshold",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_m07_med_mpc
```

```{r}
p_m05_min_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_min_05
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity\n50% threshold",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_m05_min_mpc
```

```{r}
p_m05_med_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_median_05
    )
  ) +
  labs(
    x = "Median metapopulation capacity\n50% threshold",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_m05_med_mpc
```

###  delta
```{r}
p_dmss_min_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_min
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dmss_min_mpc
```

```{r}
p_dmss_med_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_median
    )
  ) +
  labs(
    x = "Change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dmss_med_mpc
```

```{r}
p_dm07_min_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_min_07
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity (70% threshold)\n from baseline (ongoing harvest)",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dm07_min_mpc
```

```{r}
p_dm07_med_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_median_07
    )
  ) +
  labs(
    x = "Change in median metapopulation capacity (70% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dm07_med_mpc
```

```{r}
p_dm05_min_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_min_05
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()

p_dm05_min_mpc
```

```{r}
p_dm05_med_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_median_05
    )
  ) +
  labs(
    x ="Change in median metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dm05_med_mpc
```

### delta proportional
```{r}
p_pmss_min_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_min
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pmss_min_mpc
```

```{r}
p_pmss_med_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_median
    )
  ) +
  labs(
    x = "Proportional change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pmss_med_mpc
```

```{r}
p_pm07_min_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_min_07
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity (70% threshold)\n from baseline (ongoing harvest)",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pm07_min_mpc
```

```{r}
p_pm07_med_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_median_07
    )
  ) +
  labs(
    x = "Proportional change in median metapopulation capacity (70% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pm07_med_mpc
```

```{r}
p_pm05_min_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_min_05
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()

p_pm05_min_mpc
```

```{r}
p_pm05_med_mpc <- ggplot(data = mpc_rs %>% filter(sp_group == "MPC")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_median_05
    )
  ) +
  labs(
    x ="Proportional change in median metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    title = "MPC species",
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pm05_med_mpc
```


## ALL Species
###  RAW
```{r}
p_mss_min_all <- ggplot(data = mpc_rs) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_min
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_mss_min_all
```

```{r}
p_mss_med_all <- ggplot(data = mpc_rs) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_median
    )
  ) +
  labs(
    x = "Median metapopulation capacity",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_mss_med_all
```

```{r}
p_m07_min_all <- ggplot(data = mpc_rs) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_min_07
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity\n70% threshold",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_m07_min_all
```

```{r}
p_m07_med_all <- ggplot(data = mpc_rs) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_median_07
    )
  ) +
  labs(
    x = "Median metapopulation capacity\n70% threshold",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_m07_med_all
```

```{r}
p_m05_min_all <- ggplot(data = mpc_rs) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_min_05
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity\n50% threshold",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_m05_min_all
```

```{r}
p_m05_med_all <- ggplot(data = mpc_rs) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = mpc_median_05
    )
  ) +
  labs(
    x = "Median metapopulation capacity\n50% threshold",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_m05_med_all
```

###  delta
```{r}
p_dmss_min_all <- ggplot(data = mpc_rs) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_min
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dmss_min_all
```

```{r}
p_dmss_med_all <- ggplot(data = mpc_rs) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_median
    )
  ) +
  labs(
    x = "Change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dmss_med_all
```

```{r}
p_dm07_min_all <- ggplot(data = mpc_rs) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_min_07
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity (70% threshold)\n from baseline (ongoing harvest)",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dm07_min_all
```

```{r}
p_dm07_med_all <- ggplot(data = mpc_rs) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_median_07
    )
  ) +
  labs(
    x = "Change in median metapopulation capacity (70% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dm07_med_all
```

```{r}
p_dm05_min_all <- ggplot(data = mpc_rs) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_min_05
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()

p_dm05_min_all
```

```{r}
p_dm05_med_all <- ggplot(data = mpc_rs) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = delta_median_05
    )
  ) +
  labs(
    x ="Change in median metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_dm05_med_all
```

### delta proportional
```{r}
p_pmss_min_all <- ggplot(data = mpc_rs) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_min
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pmss_min_all
```

```{r}
p_pmss_med_all <- ggplot(data = mpc_rs) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_median
    )
  ) +
  labs(
    x = "Proportional change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pmss_med_all
```

```{r}
p_pm07_min_all <- ggplot(data = mpc_rs) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_min_07
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity (70% threshold)\n from baseline (ongoing harvest)",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pm07_min_all
```

```{r}
p_pm07_med_all <- ggplot(data = mpc_rs) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_median_07
    )
  ) +
  labs(
    x = "Proportional change in median metapopulation capacity (70% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pm07_med_all
```

```{r}
p_pm05_min_all <- ggplot(data = mpc_rs) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_min_05
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()

p_pm05_min_all
```

```{r}
p_pm05_med_all <- ggplot(data = mpc_rs) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      fill = species_com,
      y = scn,
      x = dp_median_05
    )
  ) +
  labs(
    x ="Proportional change in median metapopulation capacity (50% threshold)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    
    fill = "Species"
  ) +
  scale_fill_viridis_d()
p_pm05_med_all
```
