---
title: "Metapopulation capacity results: Leadbeater's possum"
output:
  word_document: default
  html_document: default
---

```{r}
spti <- "Leadbeater's possum"
spfil <- "gyle"
```


```{r}
knitr::opts_chunk$set(fig.width=8, fig.height=8, echo = FALSE, message = FALSE)
```


```{r}
source("R/spartan/spartan_settings.R")
```


```{r}
library(magrittr)
library(tibble)
library(tidyr)
library(dplyr)
library(ggplot2)
```

```{r}
load(file = "output/RData/00_controls.RData")
load(file = "output/RData/13.2_mpc_results.RData")
```

```{r}
source.functions("R/functions")
```


```{r}
mpc_rs_plot <- mpc_rs %>% filter(
  sp == spfil
)


mpc_cs_plot <- mpc_cs %>% filter(
  sp == spfil
)
```

```{r}
mpc_rs_plot
```


## RCP 4.5 ACCESS1-0 EG20 and CH only

```{r}
knitr::opts_chunk$set(fig.width=6, fig.height=4, echo = FALSE, message = FALSE)
```

```{r}
p_mss_min_pevo_ch <- ggplot(data = mpc_rs_plot %>% filter(climate_model == "ACCESS1-0", rcp == "rcp45", yearid != "EG19")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_min#,
      #fill = yearid
    )
  ) +
  geom_point(
    aes(
      y = scn,
      x = mpc_min
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity",
    y = "Management scenario",
    title = spti#,
    #fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d() +
  facet_grid(
    .~yearid,
    scales = "free_x"
  ) +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 270)
  ) 

p_mss_min_pevo_ch
```

```{r}
p_mss_med_pevo <- ggplot(data = mpc_rs_plot %>% filter(climate_model == "ACCESS1-0", rcp == "rcp45", yearid != "EG19")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_median#,
      #fill = yearid
    )
  ) +
  geom_point(
    aes(
      y = scn,
      x = mpc_median
    )
  ) +
  labs(
    x = "Median metapopulation capacity",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d() +
  facet_grid(
    .~yearid,
    scales = "free_x"
  ) +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 270)
  )

p_mss_med_pevo
```


###  delta
```{r}
p_dmss_min_pevo <- ggplot(data = mpc_rs_plot %>% filter(climate_model == "ACCESS1-0", rcp == "rcp45", yearid != "EG19")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_min#,
      #fill = yearid
    )
  ) +
  geom_point(
    aes(
      y = scn,
      x = delta_min
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d() +
  facet_grid(
    .~yearid,
    scales = "free_x"
  ) +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 270)
  )

p_dmss_min_pevo
```

```{r}
p_dmss_med_pevo <- ggplot(data = mpc_rs_plot %>% filter(climate_model == "ACCESS1-0", rcp == "rcp45", yearid != "EG19")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_median#,
      #fill = yearid
    )
  ) +
  geom_point(
    aes(
      y = scn,
      x = delta_median
    )
  ) +
  labs(
    x = "Change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d() +
  facet_grid(
    .~yearid,
    scales = "free_x"
  ) +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 270)
  )

p_dmss_med_pevo
```


### delta proportional
```{r}
p_pmss_min_pevo <- ggplot(data = mpc_rs_plot %>% filter(climate_model == "ACCESS1-0", rcp == "rcp45", yearid != "EG19")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_min#,
      #fill = yearid
    )
  ) +
  geom_point(
    aes(
      y = scn,
      x = dp_min
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = spti#,
    #fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d() +
  facet_grid(
    .~yearid,
    scales = "free_x"
  ) +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 270)
  )
p_pmss_min_pevo
```

```{r}
p_pmss_med_pevo <- ggplot(data = mpc_rs_plot %>% filter(climate_model == "ACCESS1-0", rcp == "rcp45", yearid != "EG19")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_median#,
      #fill = yearid
    )
  ) +
  geom_point(
    aes(
      y = scn,
      x = dp_median
    )
  ) +
  labs(
    x = "Proportional change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d()  +
  facet_grid(
    .~yearid,
    scales = "free_x"
  ) +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 270)
  )

p_pmss_med_pevo
```




## East Gippsland pre and post fire comparison

```{r}
knitr::opts_chunk$set(fig.width=6, fig.height=4, echo = FALSE, message = FALSE)
```

###  RAW
```{r}
p_mss_min_pevo_ch <- ggplot(data = mpc_rs_plot %>% filter(climate_model == "ACCESS1-0", rcp == "rcp45", yearid != "CH")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_min,
      fill = yearid
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d(begin = 0.5) +
  # facet_grid(
  #   .~yearid,
  #   scales = "free_x"
  # ) +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 270)
  ) 

p_mss_min_pevo_ch
```

```{r}
p_mss_med_pevo <- ggplot(data = mpc_rs_plot %>% filter(climate_model == "ACCESS1-0", rcp == "rcp45", yearid != "CH")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_median,
      fill = yearid
    )
  ) +
  labs(
    x = "Median metapopulation capacity",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d(begin = 0.5) +
  # facet_grid(
  #   .~yearid,
  #   scales = "free_x"
  # ) +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 270)
  )

p_mss_med_pevo
```


###  delta
```{r}
p_dmss_min_pevo <- ggplot(data = mpc_rs_plot %>% filter(climate_model == "ACCESS1-0", rcp == "rcp45", yearid != "CH")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_min,
      fill = yearid
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d(begin = 0.5) +
  # facet_grid(
  #   .~yearid,
  #   scales = "free_x"
  # ) +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 270)
  )

p_dmss_min_pevo
```

```{r}
p_dmss_med_pevo <- ggplot(data = mpc_rs_plot %>% filter(climate_model == "ACCESS1-0", rcp == "rcp45", yearid != "CH")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_median,
      fill = yearid
    )
  ) +
  # geom_point(
  #   aes(
  #     y = scn,
  #     x = delta_median
  #   )
  # ) +
  labs(
    x = "Change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d(begin = 0.5) +
  # facet_grid(
  #   .~yearid,
  #   scales = "free_x"
  # ) +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 270)
  )

p_dmss_med_pevo
```
### delta proportional
```{r}
p_pmss_min_pevo <- ggplot(data = mpc_rs_plot %>% filter(climate_model == "ACCESS1-0", rcp == "rcp45", yearid != "CH")) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_min,
      fill = yearid
    )
  ) +
  # geom_point(
  #   aes(
  #     y = scn,
  #     x = dp_min
  #   )
  # ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d(begin = 0.5) +
  # facet_grid(
  #   .~yearid,
  #   scales = "free_x"
  # ) +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 270)
  )
p_pmss_min_pevo
```

```{r}
p_pmss_med_pevo <- ggplot(data = mpc_rs_plot %>% filter(climate_model == "ACCESS1-0", rcp == "rcp45", yearid != "CH")) +
  geom_vline(xintercept = 0) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_median,
      fill = yearid
    )
  ) +
  # geom_point(
  #   aes(
  #     y = scn,
  #     x = dp_median
  #   )
  # ) +
  labs(
    x = "Proportional change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d(begin = 0.5)  +
  # facet_grid(
  #   .~yearid,
  #   scales = "free_x"
  # ) +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 270)
  )

p_pmss_med_pevo
```


## All climate models
```{r}
knitr::opts_chunk$set(fig.width=6, fig.height=8, echo = FALSE, message = FALSE)
```

###  RAW
```{r}
p_mss_min_pevo_cm <- ggplot(data = mpc_rs_plot) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_min,
      fill = climate_model
    )
  ) +
  labs(
    x = "Minimum metapopulation capacity",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d() +
  facet_grid(
    climate_model~yearid,
    scales = "free"
  ) +
  theme(
    axis.text.x = element_text(angle = 270, size = 7),
    axis.text.y = element_text(size = 8),
    legend.position = "bottom"
  )

p_mss_min_pevo_cm
```

```{r}
p_mss_med_pevo <- ggplot(data = mpc_rs_plot) +
  geom_boxplot(
    aes(
      y = scn,
      x = mpc_median,
      fill = climate_model
    )
  ) +
  labs(
    x = "Median metapopulation capacity",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d() +
  facet_grid(
    climate_model~yearid,
    scales = "free"
  ) +
  theme(
    axis.text.x = element_text(angle = 270, size = 7),
    axis.text.y = element_text(size = 8),
    legend.position = "bottom"
  )

p_mss_med_pevo
```


###  delta climate model baseline
```{r}
p_dmss_min_pevo <- ggplot(data = mpc_cs_plot) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_min,
      fill = climate_model
    )
  ) +
  labs(
    x = "Change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d() +
  facet_grid(
    climate_model~yearid,
    scales = "free"
  ) +
  theme(
    axis.text.x = element_text(angle = 270, size = 7),
    axis.text.y = element_text(size = 8),
    legend.position = "bottom"
  )

p_dmss_min_pevo
```

```{r}
p_dmss_med_pevo <- ggplot(data = mpc_cs_plot) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_median,
      fill = climate_model
    )
  ) +
  labs(
    x = "Change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d() +
  facet_grid(
    climate_model~yearid,
    scales = "free"
  ) +
  theme(
    axis.text.x = element_text(angle = 270, size = 7),
    axis.text.y = element_text(size = 8),
    legend.position = "bottom"
  )

p_dmss_med_pevo
```


### delta proportional climate model baseline
```{r}
p_pmss_min_pevo <- ggplot(data = mpc_cs_plot) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_min,
      fill = climate_model
    )
  ) +
  labs(
    x = "Proportional change in minimum metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d()+
  facet_grid(
    climate_model~yearid,
    scales = "free"
  ) +
  theme(
    axis.text.x = element_text(angle = 270, size = 7),
    axis.text.y = element_text(size = 8),
    legend.position = "bottom"
  )

p_pmss_min_pevo
```

```{r}
p_pmss_med_pevo <- ggplot(data = mpc_cs_plot) +
  geom_vline(xintercept = 0 ) +
  geom_boxplot(
    aes(
      y = scn,
      x = dp_median,
      fill = climate_model
    )
  ) +
  labs(
    x = "Proportional change in median metapopulation capacity from baseline\n(ongoing harvest)",
    y = "Management scenario",
    title = spti,
    fill = "Landscape\n& year"
  ) +
  scale_fill_viridis_d() +
  facet_grid(
    climate_model~yearid,
    scales = "free"
  ) +
  theme(
    axis.text.x = element_text(angle = 270, size = 7),
    axis.text.y = element_text(size = 8),
    legend.position = "bottom"
  )

p_pmss_med_pevo
```

