---
title: "plant sdms"
output:
  pdf_document: default
  html_document: default
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r}
source("R/spartan/spartan_settings.R")
```



```{r}
library(dplyr)
library(dismo)
library(gbm)
library(raster)
```


```{r}
load("output/RData/16_mpc_fit_sdm.RData")
load("output/RData/17_mpc_predict_sdm.RData")
```

*Grevillea barklyana*

```{r}
sdm_results_mpc_ch %>%
  filter(sp == "grba") %>%
  pull(brt.fit) %>%
  .[[1]] %>%
  gbm.plot
```

rename layers and fix sequence

```{r}
pred_mpc %>%
  filter(
    sp == "grba",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(predmaps) %>%
  .[[1]] %>%
  .[[c(1, 20, 20, 30, 40, 51)]] %>%
  plot
```


*Leionema bilobum serrulatum*

```{r}
sdm_results_mpc_ch %>%
  filter(sp == "lese") %>%
  pull(brt.fit) %>%
  .[[1]] %>%
  gbm.plot
```

```{r}
pred_mpc %>%
  filter(
    sp == "lese",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(predmaps) %>%
  .[[1]] %>%
  .[[c(1, 20, 20, 30, 40, 51)]] %>%
  plot
```

*Persoonia arborea*

```{r}
sdm_results_mpc_ch %>%
  filter(sp == "pear") %>%
  pull(brt.fit) %>%
  .[[1]] %>%
  gbm.plot
```

```{r}
pred_mpc %>%
  filter(
    sp == "pear",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(predmaps) %>%
  .[[1]] %>%
  .[[c(1, 20, 20, 30, 40, 51)]] %>%
  plot
```


*Wittsteinia vacciniacea*

```{r}
sdm_results_mpc_ch %>%
  filter(sp == "wiva") %>%
  pull(brt.fit) %>%
  .[[1]] %>%
  gbm.plot
```

```{r}
pred_mpc %>%
  filter(
    sp == "wiva",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(predmaps) %>%
  .[[1]] %>%
  .[[c(1, 20, 20, 30, 40, 51)]] %>%
  plot
```






