---
title: "PVA Results"
output:
  word_document: default
  html_document: default
---

```{r}
knitr::opts_chunk$set(fig.width=6, fig.height=6)
```


```{r}
source("R/spartan/spartan_settings.R")
```


```{r}
#library(magrittr)
library(dplyr)
library(purrr)
library(tibble)
library(tidyr)
library(raster)
library(sp)
library(sf)

library(ggplot2)
library(forcats)
```

```{r}
load(file = "output/RData/00_controls.RData")
load(file = "output/RData/01_landscape_variables.RData")
load(file = "output/RData/02_species_occurrences.RData")
load(file = "output/RData/11.1_pva_pevo.RData")
load(file = "output/RData/11.1_pva_pevo_egb.RData")
```

```{r}
source.functions("R/functions")
```

```{r}
pva_results_pevo_both_eg <- pva_results_pevo_both_egb
```


```{r}
pevo_pva_eg <- pva_results_pevo_both_eg %>%
  dplyr::select(
    -aggmaps
  ) %>%
  mutate(
    year = ifelse(
      yearid == "EG19",
      "2019",
      "2020"
    ),
    landscape = "East Gippsland",
    yscenario = scenario,
    scenario = sub(
      pattern = "...._",
      replacement = "",
      x = scenario
    )
  )

pevo_pva_eg
```

```{r}
pevo_pva_ch <- pva_results_pevo_both %>%
  mutate(
    yscn_id = NA,
    ycscnid = NA,
    yearid = "CH",
    yscenario = NA,
    year = "2019",
    landscape = "Central Highlands"
  ) %>%
  dplyr::select(names(pevo_pva_eg))

pevo_pva_ch
```

```{r}
pevo_pva <- bind_rows(
  pevo_pva_ch,
  pevo_pva_eg
)

pevo_pva
```


```{r}
species_names_pva <- pa_data %>%
  dplyr::select(species, sp) %>%
  mutate(
    species_com = case_when(
      sp == "gyle" ~ "Leadbeater's possum",
      sp == "pevo" ~ "Greater glider",
      sp == "peau" ~ "Yellow-bellied glider",
      sp == "smle" ~ "White-footed dunnart",
      sp == "tyte" ~ "Sooty Owl",
      sp == "vava" ~ "Lace monitor"
    )
  ) %>%
  mutate(
    species_com = factor(
      x = species_com,
      levels = c(
        "Leadbeater's possum",
        "Greater glider",
        "Yellow-bellied glider",
        "White-footed dunnart",
        "Sooty Owl",
        "Lace monitor"
      )
    )
  ) %>%
  filter(!is.na(species_com))

species_names_pva
```


```{r}
scenario_names <- tribble(
  ~scenario,       ~scn,
  "TH19_rcp45_PB", "Ongoing harvest RCP4.5",
  "TH30_rcp45_PB", "Stop harvest 2030 RCP4.5",
  "TH30_rcp85_PB", "Stop harvest 2030 RCP8.5",
  "TH00_rcp45_PB", "No harvest RCP4.5",
  "TH00_rcp85_PB", "No harvest RCP8.5",
  "TH00_rcp45_NB", "No harvest no planned burning RCP4.5"
) %>%
  mutate(
    scn = factor(
      x = scn,
      levels = c(
        "Ongoing harvest RCP4.5",
        "Stop harvest 2030 RCP4.5",
        "Stop harvest 2030 RCP8.5",
        "No harvest RCP4.5",
        "No harvest RCP8.5",
        "No harvest no planned burning RCP4.5"
      )
    )
  )

scenario_names
```



```{r}
exminpop <- emp

pvr <- pevo_pva %>%
  left_join(
    y = species_names_pva,
    by = "sp"
  ) %>%
  left_join(
    y = scenario_names,
    by = "scenario"
  ) %>%
  mutate(
    scenario = fct_reorder(
      .f = scenario,
      .x = as.numeric(scn)
    ),
    sp = fct_reorder(
      .f = sp,
      .x = as.numeric(species_com)
    ),
    species = fct_reorder(
      .f = species,
      .x = as.numeric(species_com)
    )
  ) %>%
  mutate(
    emp_med = map(
      .x = emp_all,
      .f = median
    ) %>%
      unlist,
    med_pop = map(
      .x = pva,
      .f = med.pop
    ) %>%
      unlist,
    emp_95 = map(
      .x = pva,
      .f = exminpop,
      q = 0.05
    ) %>%
      unlist,
    prop_extinct = map(
      .x = pva,
      .f = nex,
      p = TRUE
    ) %>%
      unlist,
    prop_extant = 1 - prop_extinct,
    tt_ex = map(
      .x = pva,
      .f = ttex
    ),
    mean_tt_ex = map(
      .x = tt_ex,
      .f = mean,
      na.rm = TRUE
    ) %>%
      unlist
  ) %>%
  group_by(
    landscape,
    habitat,
    year
  ) %>%
  mutate(
    ref_emp = median(emp[scenario == "TH19_rcp45_PB" & climate_model == "ACCESS1-0"]),
    ref_emp_95 = median(emp_95[scenario == "TH19_rcp45_PB" & climate_model == "ACCESS1-0"]),
    ref_emp_med = median(emp_med[scenario == "TH19_rcp45_PB" & climate_model == "ACCESS1-0"]),
    ref_med_pop = median(med_pop[scenario == "TH19_rcp45_PB" & climate_model == "ACCESS1-0"]),
    ref_prop_extant = median(prop_extant[scenario == "TH19_rcp45_PB" & climate_model == "ACCESS1-0"]),
    ref_mean_tt_ex = median(mean_tt_ex[scenario == "TH19_rcp45_PB" & climate_model == "ACCESS1-0"])
  ) %>%
  ungroup %>%
  mutate(
    delta_emp = emp - ref_emp,
    delta_emp_95 = emp_95 - ref_emp_95,
    delta_emp_med = emp_med - ref_emp_med,
    delta_med_pop = med_pop - ref_med_pop,
    delta_prop_extant = prop_extant - ref_prop_extant,
    delta_mean_tt_ex = mean_tt_ex - ref_mean_tt_ex
  )

pvr
```

```{r}
# save(
#   pvr,
#   file = "output/RData/pva_summary_pevo.RData"
# )
```



## GG

```{r}
dat_pva_pevo <- pvr %>%
  filter(sp == "pevo" & cscnid == "TH00_rcp45_PB_01_ACCESS1-0")
dat_pva_pevo
```

```{r}
dp <- dat_pva_pevo %>%
  filter(
    landscape == "Central Highlands",
    habitat == "projected"
  )

p_pva_pevo_ch_p <- psr(
  popmat = dp$pva[[1]],
  stages = 0,
  ylim = c(0, 10000)
)
p_pva_pevo_ch_p

```

```{r}
dp <- dat_pva_pevo %>%
  filter(
    landscape == "Central Highlands",
    habitat == "static"
  )

p_pva_pevo_ch_s <- psr(
  popmat = dp$pva[[1]],
  stages = 0,
  ylim = c(0, 10000)
)
p_pva_pevo_ch_s
```

```{r}
dp <- dat_pva_pevo %>%
  filter(
    landscape == "East Gippsland",
    habitat == "projected",
    year == "2019"
  )

p_pva_pevo_eg_p_19 <- psr(
  popmat = dp$pva[[1]],
  stages = 0,
  ylim = c(0, 10000)
)
p_pva_pevo_eg_p_19

```

```{r}
dp <- dat_pva_pevo %>%
  filter(
    landscape == "East Gippsland",
    habitat == "static",
    year == "2019"
  )

p_pva_pevo_eg_s_19 <- psr(
  popmat = dp$pva[[1]],
  stages = 0,
  ylim = c(0, 10000)
)
p_pva_pevo_eg_s_19
```

```{r}
dp <- dat_pva_pevo %>%
  filter(
    landscape == "East Gippsland",
    habitat == "projected",
    year == "2020"
  )

p_pva_pevo_eg_p_20 <- psr(
  popmat = dp$pva[[1]],
  stages = 0,
  ylim = c(0, 10000)
)

p_pva_pevo_eg_p_20
```

```{r}
dp <- dat_pva_pevo %>%
  filter(
    landscape == "East Gippsland",
    habitat == "static",
    year == "2020"
  )

p_pva_pevo_eg_s_20 <- psr(
  popmat = dp$pva[[1]],
  stages = 0,
  ylim = c(0, 10000)
)

p_pva_pevo_eg_s_20

```
## By Landscape (ACCESS1-0 climate model only)

### raw

```{r}
p_emp_pevo_ls <- ggplot(pvr %>% filter(climate_model == "ACCESS1-0", habitat == "projected")) +
  geom_boxplot(
    aes(
      y = scn,
      x = emp,
      fill = yearid#,
      #col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Expected minimum population",
    y = "Management scenario",
    fill = "Landscape\n& year",
    title = "Greater glider"#,
    #col = "Habitat\nmodel"
  )#+
  #facet_grid(habitat~.)

p_emp_pevo_ls
```

```{r}
p_emp95_pevo_ls <- ggplot(pvr %>% filter(climate_model == "ACCESS1-0")) +
  geom_boxplot(
    aes(
      y = scn,
      x = emp_95,
      fill = yearid,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "95% Expected minimum population",
    y = "Management scenario",
    fill = "Landscape\n& year",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_emp95_pevo_ls
```

```{r}
p_empmed_pevo_ls <- ggplot(pvr %>% filter(climate_model == "ACCESS1-0")) +
  geom_boxplot(
    aes(
      y = scn,
      x = emp_med,
      fill = yearid,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Median minimum population",
    y = "Management scenario",
    fill = "Landscape\n& year",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_empmed_pevo_ls
```

```{r}
p_med_pevo_ls <- ggplot(pvr %>% filter(climate_model == "ACCESS1-0")) +
  geom_boxplot(
    aes(
      y = scn,
      x = med_pop,
      fill = yearid,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Median population",
    y = "Management scenario",
    fill = "Landscape\n& year",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_med_pevo_ls
```

```{r}
p_pex_pevo_ls <- ggplot(pvr %>% filter(climate_model == "ACCESS1-0")) +
  geom_boxplot(
    aes(
      y = scn,
      x = prop_extant,
      fill = yearid,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Probability of persistence",
    y = "Management scenario",
    fill = "Landscape\n& year",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_pex_pevo_ls
```

```{r}
p_tex_pevo_ls <- ggplot(pvr %>% filter(climate_model == "ACCESS1-0")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mean_tt_ex,
      fill = yearid,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Mean time to extinction\n(if extinct)",
    y = "Management scenario",
    fill = "Landscape\n& year",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_tex_pevo_ls
```

### delta

```{r}
p_demp_pevo_ls <- ggplot(pvr %>% filter(climate_model == "ACCESS1-0")) +
  geom_vline(xintercept = 0) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_emp,
      fill = yearid,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Change in Expected minimum population from baseline\n(ongoing harvest)",
    y = "Management scenario",
    fill = "Landscape\n& year",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_demp_pevo_ls
```

```{r}
p_demp95_pevo_ls <- ggplot(pvr %>% filter(climate_model == "ACCESS1-0", habitat == "projected")) +
  geom_vline(xintercept = 0) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_emp_95,
      fill = yearid#,
      #col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Change in 95% Expected minimum population from baseline\n(ongoing harvest)",
    y = "Management scenario",
    fill = "Landscape\n& year",
    title = "Greater glider"#,
    #col = "Habitat\nmodel"
  )#+
  #facet_grid(habitat~.)

p_demp95_pevo_ls
```

```{r}
p_dempmed_pevo_ls <- ggplot(pvr %>% filter(climate_model == "ACCESS1-0")) +
  geom_vline(xintercept = 0) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_emp_med,
      fill = yearid,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Change in median minimum population from baseline\n(ongoing harvest)",
    y = "Management scenario",
    fill = "Landscape\n& year",
    title = "Greater glider",
    col = "Habitat\nmodel"
  ) +
  facet_grid(habitat~.)

p_dempmed_pevo_ls
```

```{r}
p_dmed_pevo_ls <- ggplot(pvr %>% filter(climate_model == "ACCESS1-0")) +
  geom_vline(xintercept = 0) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_med_pop,
      fill = yearid,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Change in median population from baseline\n(ongoing harvest)",
    y = "Management scenario",
    fill = "Landscape\n& year",
    title = "Greater glider",
    col = "Habitat\nmodel"
  ) +
  facet_grid(habitat~.)

p_dmed_pevo_ls
```

```{r}
p_dpex_pevo_ls <- ggplot(pvr %>% filter(climate_model == "ACCESS1-0")) +
  geom_vline(xintercept = 0) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_prop_extant,
      fill = yearid,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Change in probability of persistence from baseline\n(ongoing harvest)",
    y = "Management scenario",
    fill = "Landscape\n& year",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_dpex_pevo_ls
```

```{r}
p_dtex_pevo_ls <- ggplot(pvr %>% filter(climate_model == "ACCESS1-0")) +
  geom_vline(xintercept = 0) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_mean_tt_ex,
      fill = yearid,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Change in mean time to extinction (if extinct)\nfrom baseline (ongoing harvest)",
    y = "Management scenario",
    fill = "Landscape\n& year",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_dtex_pevo_ls
```

## By Climate Model (Central Highlands)

### raw

```{r}
p_emp_pevo_cm <- ggplot(pvr %>% filter(landscape == "Central Highlands")) +
  geom_boxplot(
    aes(
      y = scn,
      x = emp,
      fill = climate_model,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Expected minimum population",
    y = "Management scenario",
    fill = "Climate model",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_emp_pevo_cm
```

```{r}
p_emp95_pevo_cm <- ggplot(pvr %>% filter(landscape == "Central Highlands")) +
  geom_boxplot(
    aes(
      y = scn,
      x = emp_95,
      fill = climate_model,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "95% Expected minimum population",
    y = "Management scenario",
    fill = "Climate model",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_emp95_pevo_cm
```

```{r}
p_empmed_pevo_cm <- ggplot(pvr %>% filter(landscape == "Central Highlands")) +
  geom_boxplot(
    aes(
      y = scn,
      x = emp_med,
      fill = climate_model,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Median minimum population",
    y = "Management scenario",
    fill = "Climate model",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_empmed_pevo_cm
```

```{r}
p_med_pevo_cm <- ggplot(pvr %>% filter(landscape == "Central Highlands")) +
  geom_boxplot(
    aes(
      y = scn,
      x = med_pop,
      fill = climate_model,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Median population",
    y = "Management scenario",
    fill = "Climate model",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_med_pevo_cm
```

```{r}
p_pex_pevo_cm <- ggplot(pvr %>% filter(landscape == "Central Highlands", habitat == "projected")) +
  geom_boxplot(
    aes(
      y = scn,
      x = prop_extant,
      fill = climate_model#,
      #col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Probability of persistence",
    y = "Management scenario",
    fill = "Climate model",
    title = "Greater glider"#,
    #col = "Habitat\nmodel"
  )#+
  #facet_grid(habitat~.)

p_pex_pevo_cm
```

```{r}
p_tex_pevo_cm <- ggplot(pvr %>% filter(landscape == "Central Highlands", habitat == "projected")) +
  geom_boxplot(
    aes(
      y = scn,
      x = mean_tt_ex,
      fill = climate_model,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Mean time to extinction\n(if extinct)",
    y = "Management scenario",
    fill = "Climate model",
    title = "Greater glider"#,
    #col = "Habitat\nmodel"
  )#+
  facet_grid(habitat~.)

p_tex_pevo_cm
```

### delta

```{r}
p_demp_pevo_cm <- ggplot(pvr %>% filter(landscape == "Central Highlands")) +
  geom_vline(xintercept = 0) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_emp,
      fill = climate_model,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Change in Expected minimum population from baseline\n(ongoing harvest, ACCESS1-0)",
    y = "Management scenario",
    fill = "Climate model",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_demp_pevo_cm
```

```{r}
p_demp95_pevo_cm <- ggplot(pvr %>% filter(landscape == "Central Highlands")) +
  geom_vline(xintercept = 0) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_emp_95,
      fill = climate_model,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Change in 95% Expected minimum population from baseline\n(ongoing harvest, ACCESS1-0)",
    y = "Management scenario",
    fill = "Climate model",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_demp95_pevo_cm
```

```{r}
p_dempmed_pevo_cm <- ggplot(pvr %>% filter(landscape == "Central Highlands")) +
  geom_vline(xintercept = 0) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_emp_med,
      fill = climate_model,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Change in median minimum population from baseline\n(ongoing harvest, ACCESS1-0)",
    y = "Management scenario",
    fill = "Climate model",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_dempmed_pevo_cm
```

```{r}
p_dmed_pevo_cm <- ggplot(pvr %>% filter(landscape == "Central Highlands")) +
  geom_vline(xintercept = 0) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_med_pop,
      fill = climate_model,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Change in median population from baseline\n(ongoing harvest, ACCESS1-0)",
    y = "Management scenario",
    fill = "Climate model",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_dmed_pevo_cm
```

```{r}
p_dpex_pevo_cm <- ggplot(pvr %>% filter(landscape == "Central Highlands", habitat == "projected")) +
  geom_vline(xintercept = 0) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_prop_extant,
      fill = climate_model#,
      #col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Change in probability of persistence from baseline\n(ongoing harvest, ACCESS1-0)",
    y = "Management scenario",
    fill = "Climate model",
    title = "Greater glider"#,
    #col = "Habitat\nmodel"
  )#+
  #facet_grid(habitat~.)

p_dpex_pevo_cm
```

```{r}
p_dtex_pevo_cm <- ggplot(pvr %>% filter(landscape == "Central Highlands")) +
  geom_vline(xintercept = 0) +
  geom_boxplot(
    aes(
      y = scn,
      x = delta_mean_tt_ex,
      fill = climate_model,
      col = habitat
    )
  ) +
  scale_fill_viridis_d() +
  scale_colour_manual(values = c("grey10", "grey40")) +
  labs(
    x = "Change in mean time to extinction (if extinct)\nfrom baseline (ongoing harvest, ACCESS1-0)",
    y = "Management scenario",
    fill = "Climate model",
    title = "Greater glider",
    col = "Habitat\nmodel"
  )+
  facet_grid(habitat~.)

p_dtex_pevo_cm
```

