---
title: "sdm fits central highlands"
output:
  word_document: default
  html_document: default
---

```{r}
knitr::opts_chunk$set(fig.width=6, fig.height=4)
```



```{r}
source("R/spartan/spartan_settings.R")
```


```{r}
library(dplyr)
library(purrr)
#library(tibble)
library(tidyr)
#library(magrittr)
library(ggplot2)
library(raster)
library(dismo)
library(gbm)
```

```{r}
load(file = "output/RData/00_controls.RData")
load(file = "output/RData/01_landscape_variables.RData")
#load(file = "output/RData/10_predict_SDMs_agg.RData")
load(file = "output/RData/11.0.1_hab_set.RData")
```

```{r}
source.functions("R/functions")
```


## LBP
```{r}
hab_set %>%
  filter(
    sp == "gyle",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(hab_map) %>%
  .[[1]] %>%
  .[[c(1)]] %>%
  lp()
```


```{r}
hab_set %>%
  filter(
    sp == "gyle",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(hab_map) %>%
  .[[1]] %>%
  .[[c(1, 10, 20, 30, 40, 51)]] %>%
  lp(names.attr = c("2019", "2029", "2039", "2049", "2059", "2069"), zlim = c(0, 1))
```

## GG
*problem with this image*
```{r}
hab_set %>%
  filter(
    sp == "pevo",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(hab_map) %>%
  .[[1]] %>%
  .[[c(1)]] %>%
  lp()
```


```{r}
hab_set %>%
  filter(
    sp == "pevo",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(hab_map) %>%
  .[[1]] %>%
  .[[c(1, 10, 20, 30, 40, 51)]] %>%
  lp(names.attr = c("2019", "2029", "2039", "2049", "2059", "2069"), zlim = c(0, 1))
```

## YBG

```{r}
hab_set %>%
  filter(
    sp == "peau",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(hab_map) %>%
  .[[1]] %>%
  .[[c(1)]] %>%
  lp()
```


```{r}
hab_set %>%
  filter(
    sp == "peau",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(hab_map) %>%
  .[[1]] %>%
  .[[c(1, 10, 20, 30, 40, 51)]] %>%
  lp(names.attr = c("2019", "2029", "2039", "2049", "2059", "2069"), zlim = c(0, 1))
```
## SO

```{r}
hab_set %>%
  filter(
    sp == "tyte",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(hab_map) %>%
  .[[1]] %>%
  .[[c(1)]] %>%
  lp()
```


```{r}
hab_set %>%
  filter(
    sp == "tyte",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(hab_map) %>%
  .[[1]] %>%
  .[[c(1, 10, 20, 30, 40, 51)]] %>%
  lp(names.attr = c("2019", "2029", "2039", "2049", "2059", "2069"), zlim = c(0, 1))
```

## LM
```{r}
hab_set %>%
  filter(
    sp == "vava",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(hab_map) %>%
  .[[1]] %>%
  .[[c(1)]] %>%
  lp()
```


```{r}
hab_set %>%
  filter(
    sp == "vava",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(hab_map) %>%
  .[[1]] %>%
  .[[c(1, 10, 20, 30, 40, 51)]] %>%
  lp(names.attr = c("2019", "2029", "2039", "2049", "2059", "2069"), zlim = c(0, 1))
```

## WFD
```{r}
hab_set %>%
  filter(
    sp == "smle",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(hab_map) %>%
  .[[1]] %>%
  .[[c(1)]] %>%
  lp()
```


```{r}
hab_set %>%
  filter(
    sp == "smle",
    cscnid =="TH00_rcp45_PB_01_ACCESS1-0"
  ) %>%
  pull(hab_map) %>%
  .[[1]] %>%
  .[[c(1, 10, 20, 30, 40, 51)]] %>%
  lp(names.attr = c("2019", "2029", "2039", "2049", "2059", "2069"), zlim = c(0, 1))
```