---
title: "Victorian Forest Futures: ARI HDMs"
output: html_notebook
author: GE Ryan
date: 2019-05-15
---

```{r}
library(raster)
library(dplyr)
```
# Greater Glider

```{r}
gg_hdm_1 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Greater_Glider_Spp011133")
gg_hdm_2 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Masked/Greater_Glider_Masked_2019")
gg_hdm_3 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Masked/Greater_Glider_Masked_2019.tif")

gg_hdm_1
gg_hdm_2
gg_hdm_3
```

```{r}
plot(gg_hdm_1)
```

```{r}
plot(gg_hdm_2)
```

```{r}
plot(gg_hdm_3)
```
## Leadbeaters Possum
```{r}
lb_hdm_1 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Leadbeaters_Possum_Spp011141")
lb_hdm_2 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Masked/Leadbeaters_Possum_Masked_2019")
lb_hdm_3 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Masked/Leadbeaters_Possum_Masked_20191.tif")

lb_hdm_1
lb_hdm_2
lb_hdm_3
```

```{r}
plot(lb_hdm_1)
```

```{r}
plot(lb_hdm_2)
```

```{r}
plot(lb_hdm_3)
```

## Long-footed Potoroo
```{r}
lf_hdm_1 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Long_footed_Potoroo_Spp011179")
lf_hdm_2 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Masked/Long_footeed_Potoroo_Masked_2019")
lf_hdm_3 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Masked/Long_footed_Potoroo_Masked.tif")

lf_hdm_1
lf_hdm_2
lf_hdm_3
```

```{r}
plot(lf_hdm_1)
```

```{r}
plot(lf_hdm_2)
```

```{r}
plot(lf_hdm_3)
```

## Broad-toothed Rat
```{r}
bt_hdm_1 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Broad_toothed_Rat_Spp011438")
bt_hdm_2 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Masked/Broad_toothed_Rat_Masked_2019")

bt_hdm_1
bt_hdm_2
```

```{r}
plot(bt_hdm_1)
```

```{r}
plot(bt_hdm_2)
```

## Baw Baw Frog
```{r}
bb_hdm_1 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Baw_Baw_Frog_Spp013106")
bb_hdm_2 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Masked/Baw_Baw_Frog_Masked.tif")

bb_hdm_1
bb_hdm_2
```

```{r}
plot(bb_hdm_1)
```

```{r}
plot(bb_hdm_2)
```

## Sooty Owl
```{r}
so_hdm_1 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Sooty_Owl_Spp010253")
so_hdm_2 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Masked/Sooty_Owl_Masked_2019")
so_hdm_3 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Masked/Sooty_Owl_Masked_20191.tif")

so_hdm_1
so_hdm_2
so_hdm_3
```

```{r}
plot(so_hdm_1)
```

```{r}
plot(so_hdm_2)
```

```{r}
plot(so_hdm_3)
```

## Powerful Owl
```{r}
po_hdm_1 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Powerful_Owl_Spp010248")
po_hdm_2 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Masked/Powerful_Owl_Masked_2019")
po_hdm_3 <- raster("E:/hdm_ship_1_2019-05-14/RFA_HDMs_Ship_0303019/Masked/Powerful_Owl_Masked_20191tif.tif")

po_hdm_1
po_hdm_2
po_hdm_3
```

```{r}
plot(po_hdm_1)
```

```{r}
plot(po_hdm_2)
```

```{r}
plot(gg_hdm_3)
```
